FROM python:3.10-slim

WORKDIR /app

COPY . /app

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

COPY requirements.txt requirements.txt

RUN apt-get update && apt -y upgrade 
RUN apt-get install -y libpq-dev gcc
RUN pip install --upgrade pip &&  pip install --no-cache-dir -r requirements.txt


ENTRYPOINT [ "/entrypoint.sh" ]

